### ISSUE TITLE
Not working with hooks

### ISSUE THREAD

**Issue by MrBartusek** [TimMikeladze/tsup-react-package-starter#45]
Hey, adding hooks to this example does't work.

Chage `Example.tsx` to:
```tsx
import React, { useState } from 'react';

export type ExampleProps = {
  text?: String;
};

export function Example(props: ExampleProps) {
  const [state, setState] = useState(false);

  return <div>{props.text}</div>;
}
```

![image](https://user-images.githubusercontent.com/23432278/207351010-40bb6905-06ee-4bf7-a0ee-38f3af3a73d1.png)

**Comment by TimMikeladze** [comment]
Hi @MrBartusek I'm not able to reproduce this locally. I added a hook to the example and pushed it to Github. It builds successfully in the CI environment too. https://github.com/TimMikeladze/tsup-react-package-starter/actions  

I've seen this error before but in a specific case: I was using `npm link` or `yarn link` to include a package I was developing locally in a different project. 

If this is indeed the case for you, then I suggest using https://github.com/wclr/yalc to handle the package linking process. This workaround solved this error for me and furthermore improved my overall development workflow since I started using `yalc` to manage my local packages.

**Comment by MrBartusek** [comment]
To be completely honest with you @TimMikeladze  this single comment fixed all of the issues that I've been trying to resolve for a total of 18 hours (tracked by waketime). I've tried multiple tutorials, templates, webpack, babel, tsup, rollup and even some cursed stuff like build scripts or vite. The whole issue, as you have pointed out, was caused by links or other obscure importing methods. I've just published a package to npm and imported it straight from it, without messing with it locally. It works like a charm. Thank you so much, I can finally get some good sleep.

**Comment by TimMikeladze** [comment]
@MrBartusek I am uplifted to hear that! I felt the same way when I stumbled upon a comment suggesting `yalc`, everything just worked afterwards 😄.

In fact this comment made me realize that `yalc` should be added into this starter kit. I will do that shortly.

Happy coding and glad I could help!
